use iuni;

drop table iuniLog;

-- 当天的数据，以外表保存
CREATE EXTERNAL TABLE IF NOT EXISTS `iuniLog` (
  `timestamp` BIGINT,
  `host` STRING,
  `method` STRING,
  `url` STRING,
  `protocal` STRING,
  `adId` STRING,
  `referer` STRING,
  `country` STRING,
  `area` STRING,
  `region` STRING,
  `city` STRING,
  `couty` STRING,
  `isp` STRING,
  `user` STRING,
  `vk` STRING,
  `sid` STRING,
  `time_local` STRING,
  `connection` INT,
  `connection_requests` INT,
  `request_time` FLOAT,
  `remote_addr` STRING,
  `remote_user` STRING,
  `server_name` STRING,
  `request` STRING,
  `status` STRING,
  `body_bytes_sent` INT,
  `bytes_sent` INT,
  `sent_http_content_length` INT,
  `http_referer` STRING,
  `http_user_agent` STRING,
  `http_x_forwarded_for` STRING,
  `http_cookie` STRING,
  `http_via` STRING,
  `cookie_vk` STRING,
  `cookie_uid` STRING,
  `cookie_sessionid` STRING
) COMMENT '当天的日志'
PARTITIONED BY (time INT)
ROW FORMAT DELIMITED
LOCATION '/flume/logs/use=usefull';

-- 历史数据
CREATE TABLE IF NOT EXISTS `iuniLogHistory`(
  `timestamp` BIGINT,
  `host` STRING,
  `method` STRING,
  `url` STRING,
  `protocal` STRING,
  `adId` STRING,
  `referer` STRING,
  `country` STRING,
  `area` STRING,
  `region` STRING,
  `city` STRING,
  `couty` STRING,
  `isp` STRING,
  `time_local` STRING,
  `connection` INT,
  `connection_requests` INT,
  `request_time` FLOAT,
  `remote_addr` STRING,
  `remote_user` STRING,
  `server_name` STRING,
  `request` STRING,
  `status` STRING,
  `body_bytes_sent` INT,
  `bytes_sent` INT,
  `sent_http_content_length` INT,
  `http_referer` STRING,
  `http_user_agent` STRING,
  `http_x_forwarded_for` STRING,
  `http_cookie` STRING,
  `http_via` STRING,
  `cookie_vk` STRING,
  `cookie_uid` STRING,
  `cookie_sessionid` STRING
) COMMENT '历史日志'
PARTITIONED BY (`time` INT)
ROW FORMAT SERDE
'org.apache.hadoop.hive.serde2.columnar.ColumnarSerDe'
STORED AS RCFILE;

ALTER TABLE iuniLog ADD PARTITION (time=20150801);
ALTER TABLE iuniLog ADD PARTITION (time=20150802);
ALTER TABLE iuniLog ADD PARTITION (time=20150803);
ALTER TABLE iuniLog ADD PARTITION (time=20150804);
ALTER TABLE iuniLog ADD PARTITION (time=20150805);
ALTER TABLE iuniLog ADD PARTITION (time=20150806);
ALTER TABLE iuniLog ADD PARTITION (time=20150807);
ALTER TABLE iuniLog ADD PARTITION (time=20150808);
ALTER TABLE iuniLog ADD PARTITION (time=20150809);
ALTER TABLE iuniLog ADD PARTITION (time=20150810);
ALTER TABLE iuniLog ADD PARTITION (time=20150811);
ALTER TABLE iuniLog ADD PARTITION (time=20150812);
ALTER TABLE iuniLog ADD PARTITION (time=20150813);
ALTER TABLE iuniLog ADD PARTITION (time=20150814);
ALTER TABLE iuniLog ADD PARTITION (time=20150815);
ALTER TABLE iuniLog ADD PARTITION (time=20150816);
ALTER TABLE iuniLog ADD PARTITION (time=20150817);
ALTER TABLE iuniLog ADD PARTITION (time=20150818);
ALTER TABLE iuniLog ADD PARTITION (time=20150819);
ALTER TABLE iuniLog ADD PARTITION (time=20150820);
ALTER TABLE iuniLog ADD PARTITION (time=20150821);
ALTER TABLE iuniLog ADD PARTITION (time=20150822);
ALTER TABLE iuniLog ADD PARTITION (time=20150823);
ALTER TABLE iuniLog ADD PARTITION (time=20150824);
ALTER TABLE iuniLog ADD PARTITION (time=20150825);
ALTER TABLE iuniLog ADD PARTITION (time=20150826);
ALTER TABLE iuniLog ADD PARTITION (time=20150827);
ALTER TABLE iuniLog ADD PARTITION (time=20150828);
ALTER TABLE iuniLog ADD PARTITION (time=20150829);
ALTER TABLE iuniLog ADD PARTITION (time=20150830);
ALTER TABLE iuniLog ADD PARTITION (time=20150831);

ALTER TABLE iuniLog ADD PARTITION (time=20150701);
ALTER TABLE iuniLog ADD PARTITION (time=20150702);
ALTER TABLE iuniLog ADD PARTITION (time=20150703);
ALTER TABLE iuniLog ADD PARTITION (time=20150704);
ALTER TABLE iuniLog ADD PARTITION (time=20150705);
ALTER TABLE iuniLog ADD PARTITION (time=20150706);
ALTER TABLE iuniLog ADD PARTITION (time=20150707);
ALTER TABLE iuniLog ADD PARTITION (time=20150708);
ALTER TABLE iuniLog ADD PARTITION (time=20150709);
ALTER TABLE iuniLog ADD PARTITION (time=20150710);
ALTER TABLE iuniLog ADD PARTITION (time=20150711);
ALTER TABLE iuniLog ADD PARTITION (time=20150712);
ALTER TABLE iuniLog ADD PARTITION (time=20150713);
ALTER TABLE iuniLog ADD PARTITION (time=20150714);
ALTER TABLE iuniLog ADD PARTITION (time=20150715);
ALTER TABLE iuniLog ADD PARTITION (time=20150716);
ALTER TABLE iuniLog ADD PARTITION (time=20150717);
ALTER TABLE iuniLog ADD PARTITION (time=20150718);
ALTER TABLE iuniLog ADD PARTITION (time=20150719);
ALTER TABLE iuniLog ADD PARTITION (time=20150720);
ALTER TABLE iuniLog ADD PARTITION (time=20150721);
ALTER TABLE iuniLog ADD PARTITION (time=20150722);
ALTER TABLE iuniLog ADD PARTITION (time=20150723);
ALTER TABLE iuniLog ADD PARTITION (time=20150724);
ALTER TABLE iuniLog ADD PARTITION (time=20150725);
ALTER TABLE iuniLog ADD PARTITION (time=20150726);
ALTER TABLE iuniLog ADD PARTITION (time=20150727);
ALTER TABLE iuniLog ADD PARTITION (time=20150728);
ALTER TABLE iuniLog ADD PARTITION (time=20150729);
ALTER TABLE iuniLog ADD PARTITION (time=20150730);
ALTER TABLE iuniLog ADD PARTITION (time=20150731);

ALTER TABLE iuniLog ADD PARTITION (time=20150801);
ALTER TABLE iuniLog ADD PARTITION (time=20150802);
ALTER TABLE iuniLog ADD PARTITION (time=20150803);
ALTER TABLE iuniLog ADD PARTITION (time=20150804);
ALTER TABLE iuniLog ADD PARTITION (time=20150805);
ALTER TABLE iuniLog ADD PARTITION (time=20150806);
ALTER TABLE iuniLog ADD PARTITION (time=20150807);
ALTER TABLE iuniLog ADD PARTITION (time=20150808);
ALTER TABLE iuniLog ADD PARTITION (time=20150809);
ALTER TABLE iuniLog ADD PARTITION (time=20150810);
ALTER TABLE iuniLog ADD PARTITION (time=20150811);
ALTER TABLE iuniLog ADD PARTITION (time=20150812);
ALTER TABLE iuniLog ADD PARTITION (time=20150813);
ALTER TABLE iuniLog ADD PARTITION (time=20150814);
ALTER TABLE iuniLog ADD PARTITION (time=20150815);
ALTER TABLE iuniLog ADD PARTITION (time=20150816);
ALTER TABLE iuniLog ADD PARTITION (time=20150817);
ALTER TABLE iuniLog ADD PARTITION (time=20150818);
ALTER TABLE iuniLog ADD PARTITION (time=20150819);
ALTER TABLE iuniLog ADD PARTITION (time=20150820);
ALTER TABLE iuniLog ADD PARTITION (time=20150821);
ALTER TABLE iuniLog ADD PARTITION (time=20150822);
ALTER TABLE iuniLog ADD PARTITION (time=20150823);
ALTER TABLE iuniLog ADD PARTITION (time=20150824);
ALTER TABLE iuniLog ADD PARTITION (time=20150825);
ALTER TABLE iuniLog ADD PARTITION (time=20150826);
ALTER TABLE iuniLog ADD PARTITION (time=20150827);
ALTER TABLE iuniLog ADD PARTITION (time=20150828);
ALTER TABLE iuniLog ADD PARTITION (time=20150829);
ALTER TABLE iuniLog ADD PARTITION (time=20150830);
ALTER TABLE iuniLog ADD PARTITION (time=20150831);

ALTER TABLE iuniLog ADD PARTITION (time=20150901);
ALTER TABLE iuniLog ADD PARTITION (time=20150902);
ALTER TABLE iuniLog ADD PARTITION (time=20150903);
ALTER TABLE iuniLog ADD PARTITION (time=20150904);
ALTER TABLE iuniLog ADD PARTITION (time=20150905);
ALTER TABLE iuniLog ADD PARTITION (time=20150906);

INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150601) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150601;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150602) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150602;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150603) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150603;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150604) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150604;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150605) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150605;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150606) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150606;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150607) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150607;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150608) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150608;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150609) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150609;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150610) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150610;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150611) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150611;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150612) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150612;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150613) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150613;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150614) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150614;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150615) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150615;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150616) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150616;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150617) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150617;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150618) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150618;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150619) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150619;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150620) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150620;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150621) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150621;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150622) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150622;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150623) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150623;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150624) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150624;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150625) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150625;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150626) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150626;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150627) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150627;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150628) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150628;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150629) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150629;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150630) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150630;

INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150701) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150701;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150702) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150702;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150703) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150703;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150704) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150704;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150705) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150705;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150706) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150706;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150707) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150707;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150708) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150708;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150709) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150709;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150710) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150710;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150711) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150711;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150712) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150712;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150713) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150713;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150714) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150714;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150715) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150715;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150716) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150716;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150717) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150717;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150718) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150718;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150719) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150719;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150720) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150720;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150721) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150721;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150722) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150722;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150723) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150723;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150724) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150724;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150725) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150725;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150726) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150726;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150727) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150727;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150728) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150728;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150729) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150729;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150730) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150730;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150731) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150731;

INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150801) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150801;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150802) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150802;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150803) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150803;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150804) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150804;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150805) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150805;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150806) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150806;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150807) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150807;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150808) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150808;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150809) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150809;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150810) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150810;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150811) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150811;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150812) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150812;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150813) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150813;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150814) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150814;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150815) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150815;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150816) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150816;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150817) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150817;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150818) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150818;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150819) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150819;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150820) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150820;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150821) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150821;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150822) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150822;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150823) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150823;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150824) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150824;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150825) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150825;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150826) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150826;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150827) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150827;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150828) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150828;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150829) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150829;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150830) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150830;
INSERT OVERWRITE TABLE `iuni`.`iuniLogHistory` PARTITION(time=20150831) SELECT `timestamp`, `host`, `method`, `url`, `protocal`, `adId`, `referer`, `country`, `area`, `region`, `city`, `couty`, `isp`, `time_local`, `connection` INT, `connection_requests` INT, `request_time` FLOAT, `remote_addr`, `remote_user`, `server_name`, `request`, `status`, `body_bytes_sent` INT, `bytes_sent` INT, `sent_http_content_length` INT, `http_referer`, `http_user_agent`, `http_x_forwarded_for`, `http_cookie`, `http_via`, `cookie_vk`, `cookie_uid`, `cookie_sessionid` FROM `iuni`.`iuniLog` WHERE `time` = 20150831;


